debug: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: password
    initialization-mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  tomcat:
    max-swallow-size: -1

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 623026452252328
            clientSecret: d21d478c719bea2f879717ecefc541c2





